const plugin = require('tailwindcss/plugin');

/** @type {import(`tailwindcss`).Config} */
module.exports = {
  theme: {
    screens: {
      sm: '0px',
      md: '768px',
      lg: '1024px',
    },
    colors: {
      current: 'currentColor',
      transparent: 'transparent',
      white: 'rgb(var(--white, 255 255 255))',
      black: 'rgb(var(--black, 0 0 0))',
      neutral: {
        0: 'rgb(var(--neutral-0, 255 255 255)/ <alpha-value>)',
        1: 'rgb(var(--neutral-1, 242 241 237)/ <alpha-value>)',
        2: 'rgb(var(--neutral-2, 232 230 225)/ <alpha-value>)',
        3: 'rgb(var(--neutral-3, 219 216 211)/ <alpha-value>)',
        4: 'rgb(var(--neutral-4, 89 88 85)/ <alpha-value>)',
        5: 'rgb(var(--neutral-5, 51 50 48)/ <alpha-value>)',
      },
      first: {
        1: 'rgb(var(--first-1, 242 229 255)/ <alpha-value>)',
        2: 'rgb(var(--first-2, 229 204 255)/ <alpha-value>)',
        3: 'rgb(var(--first-3, 217 178 255)/ <alpha-value>)',
        4: 'rgb(var(--first-4, 115 40 115)/ <alpha-value>)',
        5: 'rgb(var(--first-5, 77 27 77)/ <alpha-value>)',
      },
      second: {
        1: 'rgb(var(--second-1, 240 245 181)/ <alpha-value>)',
        2: 'rgb(var(--second-2, 228 237 133)/ <alpha-value>)',
        3: 'rgb(var(--second-3, 219 229 87)/ <alpha-value>)',
        4: 'rgb(var(--second-4, 80 89 36)/ <alpha-value>)',
        5: 'rgb(var(--second-5, 45 51 15)/ <alpha-value>)',
      },
      static: {
        neutral: {
          0: 'rgb(var(--static-neutral-0, 255 255 255)/ <alpha-value>)',
          4: 'rgb(var(--static-neutral-4, 89 88 85)/ <alpha-value>)',
          5: 'rgb(var(--static-neutral-5, 51 50 48)/ <alpha-value>)',
        },
        color: {
          1: 'rgb(var(--static-color-1, 77 27 77)/ <alpha-value>)',
        },
      },
      danger: {
        1: 'rgb(var(--alert-danger-1, 255 240 244)/ <alpha-value>)',
        2: 'rgb(var(--alert-danger-2, 235 207 216)/ <alpha-value>)',
        3: 'rgb(var(--alert-danger-3, 194 143 161)/ <alpha-value>)',
        4: 'rgb(var(--alert-danger-4, 153 79 106)/ <alpha-value>)',
        5: 'rgb(var(--alert-danger-5, 128 26 59)/ <alpha-value>)',
      },
      success: {
        1: 'rgb(var(--alert-success-1, 232 247 240)/ <alpha-value>)',
        2: 'rgb(var(--alert-success-2, 193 219 208)/ <alpha-value>)',
        3: 'rgb(var(--alert-success-3, 129 171 152)/ <alpha-value>)',
        4: 'rgb(var(--alert-success-4, 64 122 96)/ <alpha-value>)',
        5: 'rgb(var(--alert-success-5, 0 71 41)/ <alpha-value>)',
      },
      warning: {
        1: 'rgb(var(--alert-warning-1, 255 251 235)/ <alpha-value>)',
        2: 'rgb(var(--alert-warning-2, 223 235 94)/ <alpha-value>)',
        3: 'rgb(var(--alert-warning-3, 163 171 69)/ <alpha-value>)',
        4: 'rgb(var(--alert-warning-4, 104 111 44)/ <alpha-value>)',
        5: 'rgb(var(--alert-warning-5, 45 51 15)/ <alpha-value>)',
      },
    },
    spacing: {
      px: '1px',
      DEFAULT: 'var(--gap-default, 16px)',
      0: 'var(--size-0, 0px)',
      1: 'var(--size-1, 1px)',
      2: 'var(--size-2, 2px)',
      4: 'var(--size-4, 4px)',
      6: 'var(--size-6, 6px)',
      8: 'var(--size-8, 8px)',
      10: 'var(--size-10, 10px)',
      12: 'var(--size-12, 12px)',
      14: 'var(--size-14, 12px)',
      16: 'var(--size-16, 14px)',
      18: 'var(--size-18, 16px)',
      20: 'var(--size-20, 18px)',
      22: 'var(--size-22, 19px)',
      24: 'var(--size-24, 20px)',
      26: 'var(--size-26, 22px)',
      28: 'var(--size-28, 24px)',
      32: 'var(--size-32, 28px)',
      36: 'var(--size-36, 32px)',
      40: 'var(--size-40, 36px)',
      48: 'var(--size-48, 44px)',
      56: 'var(--size-56, 52px)',
      64: 'var(--size-64, 60px)',
      72: 'var(--size-72, 64px)',
      96: 'var(--size-96, 80px)',
      128: 'var(--size-128, 112px)',
      160: 'var(--size-160, 144px)',
      192: 'var(--size-192, 176px)',
      256: 'var(--size-256, 240px)',
      320: 'var(--size-320, 288px)',
      352: 'var(--size-352, 336px)',
      384: 'var(--size-384, 368px)',
      480: 'var(--size-480, 456px)',
      576: 'var(--size-576, 544px)',
      infinite: 'var(--size-infinite, 9999px)',
    },
    outlineWidth: {
      0: 'var(--size-0, 0px)',
      1: 'var(--size-1, 1px)',
      2: 'var(--size-2, 2px)',
      4: 'var(--size-4, 4px)',
      6: 'var(--size-6, 6px)',
      8: 'var(--size-8, 8px)',
    },
    outlineOffset: {
      0: 'var(--size-0, 0px)',
      1: 'var(--size-1, 1px)',
      2: 'var(--size-2, 2px)',
      4: 'var(--size-4, 4px)',
      6: 'var(--size-6, 6px)',
      8: 'var(--size-8, 8px)',
    },
    maxWidth: ({ theme, breakpoints }) => ({
      ...theme('spacing'),
      none: 'none',
      full: '100%',
      min: 'min-content',
      max: 'max-content',
      fit: 'fit-content',
      prose: '65ch',
      'content-max': 'var(--content-width-max, 1400px)',
      'content-md': 'var(--content-width-md, 768px)',
      'content-sm': 'var(--content-width-sm, 544px)',
      ...breakpoints(theme('screens')),
    }),
    margin: ({ theme }) => ({
      page: 'var(--margin-page, 16px)',
      auto: 'auto',
      ...theme('spacing'),
    }),
    padding: ({ theme }) => ({
      page: 'var(--margin-page, 16px)',
      auto: 'auto',
      ...theme('spacing'),
    }),
    borderRadius: {
      none: 'var(--border-radius-none, 0px)',
      xs: 'var(--border-radius-xs, 6px)',
      sm: 'var(--border-radius-sm, 16px)',
      md: 'var(--border-radius-md, 28px)',
      lg: 'var(--border-radius-lg, 24px)',
      button: 'var(--border-radius-button, 9999px)',
      toggle: 'var(--border-radius-toggle, 9999px)',
      input: 'var(--border-radius-input, 10px)',
      card: 'var(--border-radius-card, 16px)',
      round: '9999px',
    },
    borderWidth: {
      0: '0px',
      1: 'var(--border-size-1, 1px)',
      2: 'var(--border-size-2, 2px)',
      3: 'var(--border-size-3, 3px)',
      4: 'var(--border-size-4, 4px)',
      5: 'var(--border-size-5, 5px)',
      6: 'var(--border-size-6, 6px)',
      8: 'var(--border-size-8, 8px)',
      10: 'var(--border-size-10, 10px)',
    },
    strokeWidth: {
      0: '0',
      1: '1',
      1.5: '1.5',
      2: '2',
    },
    fontFamily: {
      first: 'var(--font-family-first, "Archivo", sans-serif)',
      second: 'var(--font-family-second, "ui-sans-serif")',
    },
    fontWeight: {
      heading: 'var(--font-weight-heading, 600)',
      body: 'var(--font-weight-body, 500)',
      thin: 'var(--font-weight-thin, 400)',
      navButton: 'var(--font-weight-nav-button, 500)',
      button: 'var(--font-weight-button, 500)',
      bold: 'var(--font-weight-bold, 600)',
    },
    lineHeight: ({ theme }) => ({
      ...theme('spacing'),
      normal: 'var(--line-height, 1.5)',
      short: 'var(--line-height-short, 1.2)',
      fit: '1em',
    }),
    fontSize: ({ theme }) => ({
      ...theme('spacing'),
      '3xs': ['var(--font-size-3xs, 12px)'],
      '2xs': ['var(--font-size-2xs, 14px)'],
      xs: ['var(--font-size-xs, 16px)'],
      sm: ['var(--font-size-sm, 18px)'],
      md: ['var(--font-size-md, 20px)'],
      lg: ['var(--font-size-lg, 22px)'],
      xl: ['var(--font-size-xl, 24px)'],
      '2xl': ['var(--font-size-2xl, 28px)'],
      '3xl': ['var(--font-size-3xl, 30px)'],
      '4xl': ['var(--font-size-4xl, 32px)'],
    }),
    letterSpacing: {
      normal: 'var(--letter-spacing, 0.05px)',
    },
    boxShadow: {
      focus: 'var(--shadow-focus, 0 4px 14px rgba(51, 50, 48, 0.16))',
      lg: 'var(--shadow-lg, 0 4px 32px 0 rgba(51, 50, 48, 0.16))',
      interactive: 'var(--shadow-interactive-hover, 0 0 4px rgba(51, 50, 48, 0.16))',
      none: 'none',
    },
    dropShadow: {
      sm: 'var(--shadow-sm, 0 1px 1px rgba(51, 50, 48, 0.16))',
      lg: 'var(--shadow-lg, 0 4px 32px rgba(51, 50, 48, 0.16))',
      interactive: 'var(--shadow-interactive-hover, 0 0 4px rgba(51, 50, 48, 0.16))',
      none: 'none',
    },
    boxShadowColor: {
      neutral: 'var(--neutral-5, rgb(51 50 48))',
      first: 'var(--first-5, rgb(77 27 77))',
    },
  },
  plugins: [
    plugin(function ({ addBase, theme, addComponents }) {
      addComponents({
        '.box': {
          borderRadius: 'var(--border-radius-card, 16px)',
          padding: 'var(--size-36, 32px)',
        },
      });
      addBase({
        html: {
          fontFamily: theme('fontFamily.first'),
          letterSpacing: theme('letterSpacing.normal'),
        },
        h1: {
          fontSize: theme('fontSize.4xl'),
          fontWeight: theme('fontWeight.heading'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        h2: {
          fontSize: theme('fontSize.3xl'),
          fontWeight: theme('fontWeight.heading'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        h3: {
          fontSize: theme('fontSize.2xl'),
          fontWeight: theme('fontWeight.heading'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        h4: {
          fontSize: theme('fontSize.xl'),
          fontWeight: theme('fontWeight.heading'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        h5: {
          fontSize: theme('fontSize.lg'),
          fontWeight: theme('fontWeight.heading'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        h6: {
          fontSize: theme('fontSize.md'),
          fontWeight: theme('fontWeight.heading'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        label: {
          fontSize: theme('fontSize.xs'),
          fontWeight: theme('fontWeight.body'),
          lineHeight: theme('lineHeight.short'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        a: {
          fontSize: theme('fontSize.xs'),
          fontWeight: theme('fontWeight.body'),
          lineHeight: theme('lineHeight.normal'),
          textDecoration: 'underline',
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        p: {
          fontSize: theme('fontSize.xs'),
          fontWeight: theme('fontWeight.body'),
          lineHeight: theme('lineHeight.normal'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
        li: {
          fontSize: theme('fontSize.xs'),
          fontWeight: theme('fontWeight.body'),
          lineHeight: theme('lineHeight.normal'),
          color: 'rgb(var(--neutral-5, 51 50 48))',
        },
      });
    }),
  ],
};
